---
abstract: 'An interface to the BackPAN index'
author:
  - 'Leon Brocard <acme@astray.com>'
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  Test::Compile: '0.11'
  Test::More: '0.90'
configure_requires:
  Module::Build: '0.340201'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: BackPAN-Index
provides:
  BackPAN::Index:
    file: lib/BackPAN/Index.pm
    version: '0.42'
  BackPAN::Index::Database:
    file: lib/BackPAN/Index/Database.pm
  BackPAN::Index::Dist:
    file: lib/BackPAN/Index/Dist.pm
  BackPAN::Index::File:
    file: lib/BackPAN/Index/File.pm
  BackPAN::Index::IndexFile:
    file: lib/BackPAN/Index/IndexFile.pm
  BackPAN::Index::Release:
    file: lib/BackPAN/Index/Release.pm
  BackPAN::Index::Role::AsHash:
    file: lib/BackPAN/Index/Role/AsHash.pm
  BackPAN::Index::Role::HasCache:
    file: lib/BackPAN/Index/Role/HasCache.pm
  BackPAN::Index::Role::Log:
    file: lib/BackPAN/Index/Role/Log.pm
  BackPAN::Index::Schema:
    file: lib/BackPAN/Index/Schema.pm
  Parse::BACKPAN::Packages:
    file: lib/Parse/BACKPAN/Packages.pm
    version: '0.40'
requires:
  App::Cache: '0.37'
  Archive::Extract: '0'
  CLASS: '1.00'
  CPAN::DistnameInfo: '0.09'
  DBD::SQLite: '1.25'
  DBIx::Class: '0.08109'
  LWP::Simple: '0'
  Moo: '2.000000'
  Path::Tiny: '0.103'
  Types::Path::Tiny: '0.005'
  Types::Standard: '1.004000'
  Types::URI: '0.006'
  URI: '1.54'
  autodie: '0'
  parent: '0'
  perl: '5.008001'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=BackPAN-Index
  license: http://dev.perl.org/licenses/
  repository: http://github.com/acme/parse-backpan-packages
version: '0.42'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
